# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: http://arda.karaduman.web.tr
title: Arda Karaduman
subtitle: 
author: Arda Karaduman
simple_search: http://google.com/search
description:

description: > # this means to ignore newlines until "baseurl:"
  A Simple Resume Site.
baseurl: "" # the subpath of your site, e.g. /blog

twitter_username: ardakaraduman
github_username:  c0ze

# Build settings
markdown: kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "vendor", "Gemfile*", "locales"]
gems:
  - jekyll-assets
  - jekyll-press

assets:
  sources:
    - _assets
